plugins:
  - rubocop-rails

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.1
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "config/environments/development.rb"
    - "config/routes.rb"

Metrics/ClassLength:
  Exclude:
    - "test/controllers/kumiwake_controller_test.rb"
